@startuml
title Sequenzdiagramm für /generate-key

' Color scheme:
' #CCE5FF → API & Controller
' #F9D5E5 → Parts of Validation
' #DFFFD6 → Services
' #B7F0DC → Facades
' #FFE5B4 → Factories
' #E0E0E0 → Helpers/Utilities
' #FADBD8 → Registries

actor Client
participant JwtManagementAPI #CCE5FF
participant Controller #CCE5FF
participant JwtManagementValidator #F9D5E5
participant JwtManagementFacade #B7F0DC
participant ModelsFactory #FFE5B4
participant JwtManagementService #DFFFD6
participant ClientKeyRegistry #FADBD8
participant KeyStoreHelper #E0E0E0
participant KeyStoreLoader #E0E0E0
participant MasterKeyService #DFFFD6
participant ClientKeyEncryptor #E0E0E0
participant ClientKeyDataFactory #FFE5B4
participant ResultModelsFactory #FFE5B4
participant ResponseFactory #FFE5B4

Client -> JwtManagementAPI : POST /generate-jwt
activate JwtManagementAPI

JwtManagementAPI -> Controller : generateJwtPost(generateJwtRequest, principal)
activate Controller

Controller -> Controller : resolveClientName(principal)
Controller -> Controller : checkClientNameExists(clientName)

Controller -> JwtManagementValidator : validateGenerateJwtRequest(generateJwtRequest)
activate JwtManagementValidator

JwtManagementValidator -> ValidationService : validateText(issuedTo, FieldName.ISSUED_TO, ISSUED_TO_MAX_LENGTH, false)
activate ValidationService

ValidationService -> FieldValidator : validateNotBlank(text, name)
ValidationService -> FieldValidator : validateMaxLength(text, maxLength, name)


'TODO Finish after checking and implementing secure coding practices


Controller -> JwtManagementFacade : generateKey(clientName)
activate JwtManagementFacade

JwtManagementFacade -> ModelsFactory : buildGenerateKeyModel(clientName)
activate ModelsFactory
ModelsFactory --> JwtManagementFacade : GenerateKeyModel
deactivate ModelsFactory

JwtManagementFacade -> JwtManagementService : generateJwt(GenerateKeyModel)
activate JwtManagementService







JwtManagementService -> ResultModelsFactory : buildGenerateKeyResultModel(message)
activate ResultModelsFactory
ResultModelsFactory --> JwtManagementService : GenerateJwtResultModel
deactivate ResultModelsFactory

JwtManagementService --> JwtManagementFacade : GenerateJwtResultModel
deactivate JwtManagementService

JwtManagementFacade -> ResponseFactory : buildGenerateJwtResponse(resultModel)
activate ResponseFactory
ResponseFactory --> JwtManagementFacade : ResponseEntity<GenerateJwtResponse>
deactivate ResponseFactory

JwtManagementFacade --> Controller : ResponseEntity<GenerateJwtResponse>
deactivate JwtManagementFacade

Controller --> JwtManagementAPI : ResponseEntity<GenerateJwtResponse>
deactivate Controller

JwtManagementAPI --> Client : ResponseEntity<GenerateJwtResponse>
deactivate JwtManagementAPI

@enduml
