server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:tls/keystore.jks
server.ssl.key-store-password=CryptoMicroservice2025!
server.ssl.key-alias=localhost
server.ssl.key-store-type=JKS

logging.level.root=INFO
logging.level.com.projectwork=DEBUG
logging.file.name=logs/crypto-service.log

master.keystore.password=${MASTER_KEYSTORE_PASSWORD}
master.keystore.path=${MASTER_KEYSTORE_PATH}

client.keystore.password=${CLIENT_KEYSTORE_PASSWORD}
client.keystore.path=${CLIENT_KEYSTORE_PATH}